baseURL = 'https://side-project-portfolio.netlify.app/'
languageCode = 'en-us'
title = 'Presonal Project Site'

[params]

    [[params.projects]]
    ImgSource = "img/OnlineGoBoard.png"
    Title = "OnlineGoBoard"
    Link = "https://github.com/strawstack/OnlineGoBoard"
    Description = "Play Go online with Peer2Peer multiplayer, and the abilty to undo moves."

    [[params.projects]]
    ImgSource = "img/SVTree.png"
    Title = "SVTree"
    Link = "https://github.com/strawstack/SVTree"
    Description = "Generate trees as SVG images with live preview."

    [[params.projects]]
    ImgSource = "img/ArrivalLanguage.png"
    Title = "ArrivalLanguage"
    Link = "https://github.com/strawstack/ArrivalLanguage"
    Description = "Experience the same questions that language scientists had in the movie Arrival."

    [[params.projects]]
    ImgSource = "img/Witness.png"
    Title = "Witness"
    Link = "https://github.com/strawstack/Witness"
    Description = "Solve this puzzle from The Witness implemented with web technologies."

    [[params.projects]]
    ImgSource = "img/BezierCurveTool.png"
    Title = "BezierCurveTool"
    Link = "https://github.com/strawstack/BezierCurveTool"
    Description = "Create smooth bezier curves around reference images."
    
    [[params.projects]]
    ImgSource = "img/unwind.png"
    Title = "Unwind"
    Link = "https://github.com/strawstack/Unwind"
    Description = "Try to get all numbers to read zero without going negative."

    [[params.projects]]
    ImgSource = "img/SVGBackground.png"
    Title = "SVGBackground"
    Link = "https://github.com/strawstack/SVGBackground"
    Description = "Pleasing SVG backgrounds for all your background needs."

    [[params.projects]]
    ImgSource = "img/TileMapCreator.png"
    Title = "TileMapCreator"
    Link = "https://github.com/strawstack/TileMapCreator"
    Description = "A short description."

    [[params.projects]]
    ImgSource = "img/ColourableMap.png"
    Title = "ColourableMap"
    Link = "https://github.com/strawstack/ColourableMap"
    Description = "Using a map and a quad-tree to track where a user has hovered the mouse."

    [[params.projects]]
    ImgSource = "img/TextBubblesPhaserJS.png"
    Title = "TextBubblesPhaserJS"
    Link = "https://github.com/strawstack/TextBubblesPhaserJS"
    Description = "An implementation of Text Bubbles for use in PhaserJS. Inspired by the Legend of Zelda."

    [[params.projects]]
    ImgSource = "img/ColorWheel.png"
    Title = "ColorWheel"
    Link = "https://github.com/strawstack/ColorWheel"
    Description = "Calculating colors mathematically, and generating astetically pleasing pallets."

    [[params.projects]]
    ImgSource = "img/SnakeMath.png"
    Title = "SnakeMath"
    Link = "https://github.com/strawstack/SnakeMath"
    Description = "Math as seen from the mind of a snake. Inspored by an episode of Rick and Morty."

    [[params.projects]]
    ImgSource = "img/ManyTiles.png"
    Title = "ManyTiles"
    Link = "https://github.com/strawstack/ManyTiles"
    Description = "Light weight frame work for creating tile based adventure games."

    [[params.projects]]
    ImgSource = "img/HexColorMix.gif"
    Title = "HexColorMix"
    Link = "https://github.com/strawstack/HexColorMix"
    Description = "Mix together colors from different beakers to create new ones."

    [[params.projects]]
    ImgSource = "img/PhysicsDots.png"
    Title = "PhysicsDots"
    Link = "https://github.com/strawstack/PhysicsDots"
    Description = "A physics simulation using PhaserJS."

    [[params.projects]]
    ImgSource = "img/YahtzeeClone.png"
    Title = "YahtzeeClone"
    Link = "https://github.com/strawstack/YahtzeeClone"
    Description = "A VueJS clone of the dice game Yahtzee."

    [[params.projects]]
    ImgSource = "img/HexDice.gif"
    Title = "HexDice"
    Link = "https://github.com/strawstack/HexDice"
    Description = "A new kind of dice. Hex Dice."

    [[params.projects]]
    ImgSource = "img/IconsAreIdeas.png"
    Title = "IconsAreIdeas"
    Link = "https://github.com/strawstack/IconsAreIdeas"
    Description = "All icons are ideas and, if you put three together, you might walk away with a concept for a new project."

    [[params.projects]]
    ImgSource = "https://via.placeholder.com/500"
    Title = "Stacked"
    Link = "https://github.com/strawstack/Stacked"
    Description = "A short description."

    [[params.projects]]
    ImgSource = "https://via.placeholder.com/500"
    Title = "HashMusic"
    Link = "https://github.com/strawstack/HashMusic"
    Description = "A short description."

    [[params.projects]]
    ImgSource = "https://via.placeholder.com/500"
    Title = "SimpleSound"
    Link = "https://github.com/strawstack/SimpleSound"
    Description = "A short description."
